theme: jekyll-theme-architect
title: [srnyx's Templates]
description: [Official website for all of srnyx's Templates]
show_downloads: [true]
github:
  zip_url: https://github.com/srnyx/mc-server-templates/archive/refs/heads/main.zip
  tar_url: https://github.com/srnyx/mc-server-templates/archive/refs/heads/main.tar.gz
  another_url: https://srnyx.xyz/
